---
name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ${PWD##*/} .
      - run: ./bin/omnilint-docker-run .
      - run: ./bin/omnilint-docker-test
  dockerhub:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: tag
        run: |
          gitdescribe=$(git describe --tags)
          if [ "${gitdescribe//-g*}" = "$gitdescribe" ]; then
              tag="$gitdescribe"
              echo ::set-output name=tag::${gitdescribe}
          fi
      - run: echo tag is ${{ steps.tag.outputs.tag }}
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        if: ${{ steps.tag.outputs.tag != '' }}
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.tag.outputs.tag }}
