---
name: CI
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t ${PWD##*/} .
      - run: ./bin/omnilint-docker-run .
      - run: ./bin/omnilint-docker-test
  dockerhub:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.3
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        if: steps.version.version_tagged != ''
        with:
          push: true
          tags: ${{ github.repository }}:${{ steps.version.version_tagged }}

