---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: docker build -t ${PWD##*/} .
      - run: ./bin/omnilint-docker-run .
      - run: ./bin/omnilint-docker-test
  publish-dockerhub:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.11.0
      - uses: docker/setup-buildx-action@v2.2.1
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: ${{ steps.version.outputs.version_docker_ci != 'null' }}
      - uses: docker/build-push-action@v3.2.0
        with:
          push: ${{ steps.version.outputs.version_docker_ci != 'null' }}
          tags: ${{ github.repository }}:${{ steps.version.outputs.version_docker_ci }}
  publish-github-release:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.11.0
      - name: publish github release
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: steps.version.outputs.version_tagged != ''
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
